version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          - RAILS_ENV: test
          - RAILS_MASTER_KEY: 9ccfd6e620c80aae1bcd36c509407778
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circle_test
      - image: circleci/postgres:10.5-alpine
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore Bundle cache
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          name: Save Bundle cache
          paths:
            - ./vendor/bundle
          key: bundle-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run:
          name: Yarn install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn cache
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Database setup
          command: bundle exec rake db:drop db:create db:migrate

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
