default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>

development:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV.fetch 'POSTGRES_DB', 'alviss_development' %>

test:
  <<: *default
  host: localhost
  database: <%= ENV.fetch 'POSTGRES_DB', 'alviss_test' %>

production:
  <<: *default
  database: alviss_production
  username: revest
  password: <%= ENV['ALVISS_DATABASE_PASSWORD'] %>
